### ISSUE TITLE
line 399: should change split(':  ')  -> split(': ')

### ISSUE THREAD

**Issue by TelnetMike** [ant4g0nist/lisa.py#3]
there're two blank chars in your code after ":", while there's only one blank in lldb output, so this will not return a right result.

**Comment by ant4g0nist** [comment]
i'll modify in the new code to be committed and commit here. Thanks :+1:

**Comment by TelnetMike** [comment]
you're welcome, and the tool is very useful!

**Comment by ant4g0nist** [comment]
fixed #3
